# Generated by Django 2.1.2 on 2018-10-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0002_remove_userprofileinfo_portfolio_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='fonda',
            field=models.CharField(default='La Papa', max_length=30),
        ),
    ]
