# Generated by Django 2.1.2 on 2018-10-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0003_userprofileinfo_fonda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='fonda',
            field=models.CharField(default='', max_length=30),
        ),
    ]
