# Generated by Django 2.1.2 on 2018-10-23 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0005_userprofileinfo_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='pay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='pay_expire',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
