# Generated by Django 2.0.7 on 2018-10-31 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0007_auto_20181030_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='token',
            field=models.TextField(blank=True),
        ),
    ]
