# Generated by Django 2.0.7 on 2018-10-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0008_userprofileinfo_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='email',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='phone',
            field=models.TextField(blank=True),
        ),
    ]
